### ISSUE TITLE
FALL 2023 & SPRING 2024: Roadmap/Project Organization

### ISSUE THREAD

**Issue by andrewfagerheim** [ocean-transport/argo-intern#13]
This issue contains meeting notes, action items, and updates starting September 2023. For similar issues from previous semesters see:
- https://github.com/ocean-transport/argo-intern/issues/1
- https://github.com/ocean-transport/argo-intern/issues/8
- #10

**Comment by andrewfagerheim** [comment]
6 October 2023: Updates
-

Notes:
- Check here for the last update from the summer: https://github.com/ocean-transport/argo-intern/issues/10#issuecomment-1701800426
- Two weeks ago I started making tracer & gradient plots in density space. The function to go from depth to density space took a very long time on the sections, so I only loaded the long sections from the Atlantic and Pacific and saved them as netcdf files.
- Next I tried to calculate EKE from the datasets with density coordinates, but the fact that there are nans in every profile (since not every profile has the same density range) produces a dataset of all nans. I think this means I'll need to create the EKE dataset in depth space, convert to density space using the interpolation function, then save it. I tried to avoid this because it'll be time consuming, but I can't think of another option.
- In addition to this, there's still the outstanding question of spice definition from Smith & Ferrari 2009. This should be a broader conversation with Dhruv.

GRFP Progress:
- I've made good progress on the [personal statement](https://docs.google.com/document/d/1xAyhGl9MbzdIUSGK4gor2sxoNJ12jjvYZG9tVAU6PKQ/edit), just need to make a few final additions and lots of proofreading.
- I've made much less progress on the [research statement](https://docs.google.com/document/d/1axlLoyoEjX1vvhziDPU8E6_Em5fzzsCLndeS2D6wIds/edit), hoping to talk with Dhruv about that more today. After talking with Laura, I think I understand the structure better, I just need help talking through the content that should be included.
- Dhruv has agreed to write a letter speaking to my research experience and the proposal's science impacts, Jen has agreed to write a letter on my broader impacts/community organizing work, and Thanos has agreed to write one about academics and working with the EEE department.

Next steps: research
- [x] Ocean Sciences travel grant [due Oct 25]
- [x] organize papers in folder
- [x] ~~adapt the depth to density conversion function to also work for EKE dataset~~
- [x] plot large sections of tracer, tracer gradient, and tracer EKE in density space
- [ ] (long term) take a look at Smith & Ferrari definition of spice, compare EKEs calculated with each value

Next steps: GRFP
- [x] put finishing touches on personal statement [due Oct 20]
- [x] really dig into research statement [due Oct 20]
- [x] meet with letter writers individually and provide them with necessary materials (CV, both statements, background to GRFP judging criteria) [letters due Oct 27]

**Comment by andrewfagerheim** [comment]
27 Oct 2023: Updates
-

Notes:
- I think admin is pretty much done for the semester which is great! (GRFP, OS travel grant, and CCS grant paperwork are all submitted)
- Back to the density space plots: I've been able to make panels of tracers and tracer gradients in density space, but EKE plots have been more elusive. When I try to calculate EKE using a dataset with density coordinates, it returns a dataset with all nans, I'm assuming because there are many nans in every profile. The only remedy to this I can think of is get a dataset in depth space, interpolate it to density space, then save as a netcdf file.
- I'm a bit worried about making a new interpolation function because I don't really understand the current one in-depth. Also there's the complicating factor that the EKE dataset has an additional dimension (`EKE` which represents multiple filter scales). All this to say, I expect this to take a bit of time to untangle
- Unfortunately it doesn't seem like I'll be able to make much progress on this today because there's a generator outage from ~9AM-1PM so I can't use gyre. Instead, today you should focus on catching up on readings (take notes in obsidian!!!!!)

Next steps:
- see comment above

**Comment by andrewfagerheim** [comment]
27 Oct 2023: Updates
-

I think admin is pretty much done for the semester which is great! GRFP, OS travel grant, and CCS grant paperwork are all submitted.

Notes, density space:
- Back to the density space plots: I've been able to make panels of tracers and tracer gradients in density space, but EKE plots have been more elusive. When I try to calculate EKE using a dataset with density coordinates, it returns a dataset with all nans, I'm assuming because there are many nans in every profile. The only remedy to this I can think of is get a dataset in depth space, interpolate it to density space, then save as a netcdf file.
- I'm a bit worried about making a new interpolation function because I don't really understand the current one in-depth. Also there's the complicating factor that the EKE dataset has an additional dimension (`EKE` which represents multiple filter scales). All this to say, I expect this to take a bit of time to untangle

Notes, idealized profiles:
- I made a new notebook in the LEAP hub to create idealized profiles to look at the variance metrics. I created a large-scale exponential gradient for temperature and salinity, and added small-scale variability by adding a sine wave. I then put these profiles in an xarray dataset with density and spice so the format is similar to data loaded from Argo. 
- I've been updating my functions to work with this situation (mostly little tweaks, places I forgot to change PRES_INTERPOLATED to dim2 for example). However, there seems to be a problem with there only being one profile in this dataset that's kind of a pain. Instead, I think I should ignore the functions I've written, and write everything out from scratch in the notebook so it's all in one place.

Next steps:
- [x] convert EKE dataset to depth space
- [x] make panels of tracer, tracer gradient, and EKE
- [x] finish filtering & EKE part of idealized profiles notebook

**Comment by andrewfagerheim** [comment]
10 Nov 2023: Meeting w @dhruvbalwada 
-

Notes: density-space sections
- Most of the space in these plots is taken up by near-surface measurements, where tracers change most significantly, and the interesting signals we're looking at are crammed into the bottom of the plot. There's a few ways to address this:
  - Simply cut out densities above ~26 (then you're cutting out lots of data though)
  - Try log scale on the y axis? (probably less easy to interpret the grid though)
  - Try a WOCE style plot where the section is split into two density ranges with approximately equal height (maybe 21-26 and 26-28 for example).
- Also add a few depth contours to the plot, maybe 50m, 100m, 200m, 500m, 1000m, 1500m

Notes: simple profiles
- Goal here is to address the question: If the gradient is minimized must the EKE also be minimized? Or is this simply a pattern/connection we've seen so far?
- First focus on adding the whole workflow to filter a profile and calculate variance at different scales, then calculate EKE. After the notebook is completely set up for the profiles you've chosen, then try to adapt the shape to answer the kinds of questions we're interested in above.
- Focus on this profile test case first, it will help inform what we want to look at for density-space plots.

Next steps:
- [x] add filtering & EKE steps to simple profiles notebook
- [x] examine different profile shapes to look at connection between gradient and EKE
- [x] ~~(longer term) make a new function to interpolate an EKE dataset in depth space to density space~~
- [x] (longer term) plot sections of EKE in depth space
- [x] (longer term) update y axis of depth space sections to be more proportional

**Comment by andrewfagerheim** [comment]
23 Jan 2024: Meeting w @dhruvbalwada 
-

Notes:
- Ideal profiles notebook is almost complete. Again, the focus here is to control how much noise we put into a profile, then test how our methods treat this. In other words, the same amount of noise will be applied to the entire profile. If the variance metric shows equal variance along the whole profile, this indicates the pattern we're seeing in Argo sections is an actual science result. If the variance metric is lower where the profile's gradient is lowest, this indicates some kind of bias in the methods (because we know we added the same amount of noise/variance to the whole profile.)
- For OSM: [CCS poster from last spring](https://drive.google.com/file/d/10SjYEo3N-MZAbLJ6pxHqrbpuA8zzOWQe/view?usp=sharing) seems to be a decent jumping off point. Here are some more specific thoughts 
  - Motivation seems decent. Maybe add section from glider and/or Argo (connects theoretical models to actual data)
  - Currently the poster is VERY text heavy—especially with an entire block of text under discussion. Probably just cut that whole box and instead have bullets (MAX) next to the figures in results.
  - Before printing, definitely try to have the ideal profiles notebook done so we can have a better understanding of what confidence to place in the results. Additionally, it would be great to have density-space plots, I'm hoping this isn't incredibly complicated.

Next steps: 
_This might be a bit ambitious, but I think it's possible. Either way, in the next two weeks you need to define what will be on the OSM poster._
- [x] finish simple profiles notebook [Tuesday 1/30]
- [x] apply to HPC summer program [Wednesday 1/31]
- [ ] update methods section of manuscript [next Friday 2/2]
- [x] create density space section plots of variance [next Tuesday 2/6]
- [x] create first draft of OSM poster [next Friday 2/9]
- [x] PRINT OSM POSTER [FRIDAY 2/16]

**Comment by andrewfagerheim** [comment]
30 Jan 2024: Meeting w @dhruvbalwada 
-

Notes:
- From this really qualitative example, it seems like the cross term is not tending toward zero, which is why the large-scale gradient is influencing our effort to quantify EKE alone. (ie in the decomposition, this final term is dominating the signal, when we instead hope it would cancel completely.)
      $T = \overline{T} + T'$
      $T^2= \overline{T}^2 + T'^2 + 2(\overline{T})(T')$

- There are lots of things to test here, and I'm not going to remember to write everything down in this note. But here are the most important things to start with:
  - test the assumption that the cross term is not zero by running through the steps for: 
      $T --> T^2 --> <T^2>
  - test a new EKE definition with phase averaging (hopefully I put the bars in the right place):
      $EKE^N = <\overline{T^2}> - <\overline{T}>^2$
  - test just the definition of variance (ie no filtering at all):
      $Variance = \overline{T^2} - \overline{T}^2$
- Also look up a new paper from Aluie's group? Dhruv said it might be more practical than the last when it comes to understanding these variance and filtering terms when applying it to large-scale spatial data and averaging

Next steps:
- [x] apply to HPC summer program [Wednesday 1/31]
- [ ] read Aluie paper [Friday? 2/2]
- [x] update simple profiles notebook with these checks [Friday 2/2]
- [ ] update methods section of manuscript [Saturday 2/3]

**Comment by andrewfagerheim** [comment]
13 February 2024: Meeting w @dhruvbalwada 
-

Notes:
- Seems like ensemble variance method alone (without filtering) works to remove the large-scale gradient which is good! The problem is not filtering means we're not getting information about scale, which is a fairly important piece of the story we're trying to tell.
- In addition, when I tried applying this method to sample Argo profiles, it was still dominated by a peak in the region (I'm assuming) corresponds to the large-scale gradient. This is a bit worrying because it might suggest there's something the ideal notebook isn't capturing? But maybe small-scale variation happens to peak where the large-scale gradient is minimized?
- So, there's a lot to think through before putting the poster together. Namely:
  - Does taking an ensemble average across sin waves with many phases go to zero as you increase the number of waves?
  - Does combining ensemble averaging with Steinberg's method allow for analysis by scale while also removing the large-scale gradient? (For this: instead of applying Steinberg's methods to T(z), try with T'(z))
  - How do these method updates impact section plots of Argo data?
- Start with the ideal profiles notebook. Test the ensemble averaging across many profiles, then try applying Steinberg's methods to T'(z). Then clean up the notebook, improving notes and documentation along the way. Send this to Dhruv.
- Then move to Argo data. Load two new sections (one in the Pacific, one in the Atlantic) that are 5° of latitude across and divide them into 5° x 5° bins. Test whatever ensemble averaging method works considering above approach. If there's time, repeat with 2° x 2° bins. 

Next steps:
- [x] update ideal profiles notebook with the following items:
  - [x] ensemble averaging with phase offsets of _n_ profiles [less urgent]
  - [x] Steinberg's methods with T'(z) [TUESDAY]
  - [x] improve notebook readability [TUESDAY]
- [x] test on Argo data:
  - [x] load new boxes in Atlantic and Pacific [TUESDAY]
  - [x] apply method to create new sections [WEDNESDAY]
- [x] get poster printed:
  - [x] update motivation box with glider section [WEDNESDAY]
  - [x] add new methods and results boxes [THURSDAY]
  - [x] maybe small conclusions box? or future work? [THURSDAY]
  - [x] any last changes, send poster for printing [FRIDAY]

**Comment by andrewfagerheim** [comment]
1 March 2024: Meeting w whole group
-

Notes:
- There are a few things to be working on next, including refining the plots. This includes
  - making plots with two panels: variance with depth as y-coordinate next to density as y-coordinate. Also add smoothed contours of isopycnals and depth lines alternating with the y-coordinate, and LABEL. This will make it easier to compare features between the two
  - testing sensitivity of interpolation to density, particularly with the grid chosen. Is 1000 points really enough? Or is this smoothing features we want to study, particularly at higher density where depth information is compressed. First, check by plotting isopycnals in depth space to see how close they actually are. If it seems like something is off, then you can either try: (1) interpolating using two grids (coarser at lower density and finer at higher density), or (2) using a logarithmic distribution instead of a linear one.
- Once these more immediate thoughts are sorted out, there are longer-term steps that should be considered. In particular, I'm thinking about
  - the interpolation function is really slow and it would be good to look into why (and ideally fix this before doing much else really).
  - loading Argo data for the whole globe. I'd like to make a global plots of: (1) pick a depth range and plot the summed variance, I think this will be a useful metric for comparing regions
  - I also think it would be interesting to pick an isopycnal and plot its variance globally, I imagine this will suggest areas of variance "formation"? and how it spreads along an isopycnal
- Also, you need to reread Smith & Ferrari 2009 and understand what tracer they're tracking. It's spice, but normalized for horizontal gradients? Is that right? Anyway, read into this and test this definition with Argo data. (Also keep in mind the filter scale question -- does the horizontal-vertical relationships they suggest point to what filter scales we should consider?)
- As always, remember to keep chipping away at the paper draft! I've started working on drafting notes for the methods section, this could use more attention. For some reason, I feel like whenever I sit down to write this, I lose all ability to use language. Maybe conceptualize this as more sketching/drafting information than "writing a paper," just get thoughts out for now.

Next steps:
- [ ] side-by-side depth and density plots
- [ ] check rho-grid spacing at high density
- [ ] download Argo data globally
- [ ] completely update methods section
- [ ] reread Smith & Ferrari 2009 (paying attention to tracer definitions and scales of vertical variance)

**Comment by andrewfagerheim** [comment]
29 March 2024: Updates
-

Notes:
- At our last meeting, Dhruv mentioned a few items to think about, including:
  - Currently for density space plots, I first compute variance in depth space then interpolate this to density. Instead, try first interpolating to density space, then computing the variance terms. Do these produce different results? Also try above comment on interpolation related to the grid space (1000 points might be fine in theory, but really the signals we're interested in are confined to a much smaller density range).
  - Read Ferrari & Polzin 2005 first, then Smith & Ferrari 2009 second. Dhruv's notes on Ferrari 2005 are [here](https://github.com/ocean-transport/argo-intern/issues/12#issuecomment-2027365757). In particular, watch out for the ratio comparing variance production by eddies and by turbulence.
 
Next steps:
- [ ] investigate density space plots (look at this comment and the one above)
- [ ] think about ratio of mean and mesoscale terms
- [ ] summer school applications!
- [ ] applying to ocean mixing GRC?

**Comment by andrewfagerheim** [comment]
Closing this and opening a new issue for the new semester
